### PR TITLE
Adds responsive docking

### PR DESCRIPTION
**Pull request by jpstrikesback**
Hey, I found your awesome work to get a push/displace drawer working! I needed that, and responsive docking, together so I implemented a new drawerType called 'responsive' that works with a new drawerResponsiveWidth prop to choose between docking (squishes content via flex) / push. I'm submitting a PR here as opposed to the main repo in case if you were going to PR your work.

### CODE REVIEW

**Comment by blackneck** [comment]
Hey, @jpstrikesback , thanks for this awesome PR! Going to merge it.
Glad to hear you appreciate my work. Got no plans to PR my work into main repo for now, but I'll think about it

**Comment by jpstrikesback** [comment]
Cheers!

**Comment by jpstrikesback** [comment]
We might PR this if you're not planning on it, obviously pointing to your great work here!!

**Comment by blackneck** [comment]
@jpstrikesback great! sure feel free to do anything!
Glad to help you guys :)

**Pull request merged**
